### ISSUE TITLE
http: panic serving [::1]:65373 runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by hedrick** [gophercises/urlshort#10]
So I completed the exercise and ran into this error when I would `go run main/main.go`

As a sanity check, I pulled down the solution branch and tried to build but still get the same error.

Here is the full log:

`2018/01/22 09:14:56 http: panic serving [::1]:65373: runtime error: invalid memory address or nil pointer dereference
goroutine 19 [running]:
net/http.(*conn).serve.func1(0xc42009a780)
        /usr/local/Cellar/go/1.9.2/libexec/src/net/http/server.go:1697 +0xd0
panic(0x124ff40, 0x13f9de0)
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x283
net/http.HandlerFunc.ServeHTTP(0x0, 0x13d0da0, 0xc420126000, 0xc420120000)
        /usr/local/Cellar/go/1.9.2/libexec/src/net/http/server.go:1918 +0x3f
net/http.serverHandler.ServeHTTP(0xc420088f70, 0x13d0da0, 0xc420126000, 0xc420120000)
        /usr/local/Cellar/go/1.9.2/libexec/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc42009a780, 0x13d1220, 0xc42008c200)
        /usr/local/Cellar/go/1.9.2/libexec/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.9.2/libexec/src/net/http/server.go:2720 +0x288`

I tried to set up Delve earlier in the day and that's about the only thing I can think of that may be causing the issue as I was having problems with the self-signed certificate but I can't imagine that a debugger would be causing the issue.

That said, I double checked other Go projects on my local machine that use the http package and they seem to be working fine.

**Comment by joncalhoun** [comment]
Can you share your code?

**Comment by mdsiebler** [comment]
Hi, sorry to bother but I ran into the same issue trying to run your solution code.

**Comment by joncalhoun** [comment]
How are you running the solution, and can you share the full error? Specifically, is there a line number pointed to in my code?

I just grabbed the solution branch to double check and its working locally so I'm not 100% sure what is up 😦

**Comment by mdsiebler** [comment]
This is how i run it:  and what i see is below
note i had to change the port cause of conflicts on my latop
I get the panic after sending a request as below

$ go run main/main.go
Starting the server on :8185
2018/08/30 13:20:10 http: panic serving 127.0.0.1:63856: runtime error: invalid memory address or nil pointer dereference
goroutine 18 [running]:
net/http.(*conn).serve.func1(0xc04205e960)
        C:/Go/src/net/http/server.go:1726 +0xd7
panic(0x63d680, 0x7e11a0)
        C:/Go/src/runtime/panic.go:505 +0x237
net/http.HandlerFunc.ServeHTTP(0x0, 0x6bf980, 0xc04211c000, 0xc042112000)
        C:/Go/src/net/http/server.go:1947 +0x46
net/http.serverHandler.ServeHTTP(0xc04206ad00, 0x6bf980, 0xc04211c000, 0xc042112000)
        C:/Go/src/net/http/server.go:2694 +0xc3
net/http.(*conn).serve(0xc04205e960, 0x6bfa80, 0xc04201a0c0)
        C:/Go/src/net/http/server.go:1830 +0x658
created by net/http.(*Server).Serve
        C:/Go/src/net/http/server.go:2795 +0x282


C:\Users\IBM_ADMIN>curl http://127.0.0.1:8185/test
curl: (52) Empty reply from server

Thanks for your reply

**Comment by joncalhoun** [comment]
Honestly I'm not sure what is going on. None of the trace points to code we wrote - it is all in the standard library - so I have no idea what is causing the issue off the top of my head.

Are you using the exact code from the solution branch of the repo, or did you code it yourself using the video? The more you can share, including source code on the off-chance there is a minor variation, the better.

I also see that you are on Windows but am uncertain how that would affect things. I can't imagine you are the first person to use windows for this exercise.

**Comment by mdsiebler** [comment]
Hi yes, I am using the downloaded code. Here is is attached.
[urlshort.zip](https://github.com/gophercises/urlshort/files/2346144/urlshort.zip)
Thanks

**Comment by joncalhoun** [comment]
Oh, you have to actually look at the solution branch - https://github.com/gophercises/urlshort/tree/solution - to get the solution code. The master branch doesn't have it so people can clone the repo and try on their own without first seeing the solution. The code you are running returns `nil` for a few things and this is what is causing the error I suspect.

**Comment by mdsiebler** [comment]
ok thanks

**Comment by joncalhoun** [comment]
No problem. If you keep having issues let me know, but I closed this issue since I think that is the underlying problem.

**Comment by kenseii** [comment]
Is there a solution for this issue?
I am facing it on go v1.10.4, also the solution code returns the same error.

2019/04/01 01:52:37 http: panic serving 127.0.0.1:38052: runtime error: invalid memory address or nil pointer dereference
goroutine 12 [running]:
net/http.(*conn).serve.func1(0xc4201b8320)
        /usr/lib/go-1.10/src/net/http/server.go:1726 +0xd0
panic(0x64e7e0, 0x7ff400)
        /usr/lib/go-1.10/src/runtime/panic.go:502 +0x229
net/http.HandlerFunc.ServeHTTP(0x0, 0x6d24e0, 0xc4201c22a0, 0xc4201bc500)
        /usr/lib/go-1.10/src/net/http/server.go:1947 +0x3f
net/http.serverHandler.ServeHTTP(0xc42009ed00, 0x6d24e0, 0xc4201c22a0, 0xc4201bc500)
        /usr/lib/go-1.10/src/net/http/server.go:2697 +0xbc
net/http.(*conn).serve(0xc4201b8320, 0x6d26a0, 0xc420024700)
        /usr/lib/go-1.10/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /usr/lib/go-1.10/src/net/http/server.go:2798 +0x27b

**Comment by productdana** [comment]
I'm still having the same runtime error after cloning the solution branch and running it. Is there other set up required? @joncalhoun

**Comment by joncalhoun** [comment]
Here's what I just did and it worked for me:

```
mkdir -p $GOPATH/src/github.com/gophercises
cd $GOPATH/src/github.com/gophercises
git clone git@github.com:gophercises/urlshort.git
cd urlshort
git checkout solution
go run main/main.go
```

Your error suggests a nil pointer, which as far as I can tell means you are not in the right branch. Master has a nil pointer because some things are implemented in the exercise.

**Comment by maylortaylor** [comment]
I am also getting this exact issue when using the `solution` code.

```

Starting the server on :8080
2019/10/18 16:06:28 http: panic serving [::1]:50460: runtime error: invalid memory address or nil pointer dereference
goroutine 19 [running]:
net/http.(*conn).serve.func1(0xc00006ebe0)
        c:/go/src/net/http/server.go:1767 +0x140
panic(0x692c60, 0x8fe0a0)
        c:/go/src/runtime/panic.go:679 +0x1c0
net/http.HandlerFunc.ServeHTTP(0x0, 0x74cc00, 0xc000128000, 0xc00010c000)
        c:/go/src/net/http/server.go:2007 +0x46
net/http.serverHandler.ServeHTTP(0xc0000de000, 0x74cc00, 0xc000128000, 0xc00010c000)
        c:/go/src/net/http/server.go:2802 +0xab
net/http.(*conn).serve(0xc00006ebe0, 0x74d0c0, 0xc000052080)
        c:/go/src/net/http/server.go:1890 +0x87c
created by net/http.(*Server).Serve
        c:/go/src/net/http/server.go:2927 +0x395
2019/10/18 16:06:28 http: panic serving [::1]:50461: runtime error: invalid memory address or nil pointer dereference
goroutine 34 [running]:
net/http.(*conn).serve.func1(0xc0000f4000)
        c:/go/src/net/http/server.go:1767 +0x140
panic(0x692c60, 0x8fe0a0)
        c:/go/src/runtime/panic.go:679 +0x1c0
net/http.HandlerFunc.ServeHTTP(0x0, 0x74cc00, 0xc00015e000, 0xc00010e000)
        c:/go/src/net/http/server.go:2007 +0x46
net/http.serverHandler.ServeHTTP(0xc0000de000, 0x74cc00, 0xc00015e000, 0xc00010e000)
        c:/go/src/net/http/server.go:2802 +0xab
net/http.(*conn).serve(0xc0000f4000, 0x74d0c0, 0xc0000b6300)
        c:/go/src/net/http/server.go:1890 +0x87c
created by net/http.(*Server).Serve
        c:/go/src/net/http/server.go:2927 +0x395
2019/10/18 16:06:28 http: panic serving [::1]:50463: runtime error: invalid memory address or nil pointer dereference
goroutine 20 [running]:
net/http.(*conn).serve.func1(0xc00006ec80)
        c:/go/src/net/http/server.go:1767 +0x140
panic(0x692c60, 0x8fe0a0)
        c:/go/src/runtime/panic.go:679 +0x1c0
net/http.HandlerFunc.ServeHTTP(0x0, 0x74cc00, 0xc00015e0e0, 0xc00010c100)
        c:/go/src/net/http/server.go:2007 +0x46
net/http.serverHandler.ServeHTTP(0xc0000de000, 0x74cc00, 0xc00015e0e0, 0xc00010c100)
        c:/go/src/net/http/server.go:2802 +0xab
net/http.(*conn).serve(0xc00006ec80, 0x74d0c0, 0xc0000521c0)
        c:/go/src/net/http/server.go:1890 +0x87c
created by net/http.(*Server).Serve
        c:/go/src/net/http/server.go:2927 +0x395
```

**Comment by joncalhoun** [comment]
I'm not trying to be unhelpful, but that is literally not possible if you are in the correct branch, so I'm not sure how to help you 😦

**Comment by tmcentee** [comment]
I had a similar error. I then realized that somehow I was working outside of my $GOPATH. I think I may have `git cloned` the repo in the wrong directory. 

Moving everything back into the proper `$GOPATH/src/github.com/gophercises` structure worked fine.

**Comment by dsl2022** [comment]
The issue is very simple, because the main.go file is requiring the urlshort package from the handler.go file, inside the import statement, it's getting it from "github.com/gophercises/urlshort", which does not exist if you just clone it down from the repo to a local directory that is outside the GOPATH. Newer Go version allow you to use Module, so you don't have to always put your project inside the GOPATH. So, you need to point package import to the local handler.go file for the urlShort package to run properly. 

the easiest way to fix it is to delete `"github.com/gophercises/urlshort"` from the input then save the file,  Go will automatically find its source and replaced it with something like `urlshort "quiz_app/urlShortener/urlShortener2"`. note: `quiz_app/urlShortener/urlShortener2` is the path where I cloned and stored the project. Now if you run it, it will work because it knows where urlShort package is.

**Comment by rkbright** [comment]
I was having the same issue. As others have suggested, just move your project to a sub folder in your $GOPATH and it should work fine. 

~$ mv path/to/urlshort $GOPATH/src

**Comment by mblogger** [comment]
> I was having the same issue. As others have suggested, just move your project to a sub folder in your $GOPATH and it should work fine.
> 
> ~$ mv path/to/urlshort $GOPATH/src

+1
