### ISSUE TITLE
Relevant links don't work on gophersices.com

### ISSUE THREAD

**Issue by milangrahovac** [gophercises/urlshort#13]
Thank you for your course! It's very helpful.

When you provide relevant links at GitHub, they work well. Probably, GitHub resolves relevant links correctly, e.g. `(handler.go)` it resolves to `https://github.com/gophercises/urlshort/blob/master/handler.go`. 

On the other hand, on the website itself (e.g. on https://gophercises.com/exercises/urlshort) such links are resolved as relevant: `(handler.go)` it resolves to `https://gophercises.com/exercises/handler.go` and this page obviously doesn't exist.

The simplest way is probably to always use absolute paths. But maybe it might make sense to add some resolver to gophercises.com to resolve such URLs automatically?

Thank you again.

**Comment by joncalhoun** [comment]
Thanks for pointing this out. I've been trying to use absolute links in recent exercises but I'm human and I forget 😰. I'll address this and your other PR when I get time (may be next week tho)
