### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bit-mentat** [gophercises/urlshort#42]
After several attempts at my own solution, I decided to follow the [tutorial](https://www.youtube.com/watch?v=s7zZEkYMOiU&t=707) , but after implementing the MapHandler, commenting out yaml related code, I still cannot get the "hello world" when calling localhost:8080. 

I found some solutions for similar problems, but usually they require logging an error. However I cannot seem to figure out which net/http function in the code has this.

**Comment by joncalhoun** [comment]
The solution is in the solution branch - https://github.com/gophercises/urlshort/tree/solution
